config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
    resources :jokes
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'home#index'
    get '/random', to: 'jokes#random', as: :random_joke
    post '/search', to: 'jokes#search', as: :search_joke
    post '/category', to: 'jokes#category', as: :category_joke
  end
end

app/models/api/chuck.rb
class Api::Chuck
    include HTTParty
    base_uri 'api.chucknorris.io/jokes'

    def random
      response = self.class.get("/random")
      results = []
      joke = Api::Joke.new(response['icon_url'],response['url'],response['value'])
      results.push(joke)
      results
    end

    def search(query)
      response = self.class.get("/search?query=#{query}")
      results = []
      count = response['total'].to_i
      count.times.each do |i|
        joke = Api::Joke.new(response['result'][i]['icon_url'],response['result'][i]['url'],response['result'][i]['value'])
        results.push(joke)
        i += 1
      end
      results
    end

    def category(category)
      response = self.class.get("/random?category=#{category}")
      puts response
      results = []
      joke = Api::Joke.new(response['icon_url'],response['url'],response['value'])
      results.push(joke)
      results
    end

    def categories
      response = self.class.get("/categories")
    end

end

app/models/api/joke.rb
class Api::Joke
  attr_accessor :icon_url,:url,:value
  def initialize(icon_url,url,value)
    @icon_url = icon_url
    @url = url
    @value = value
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joke.rb
class Joke < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end
  
  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    chuck = Api::Chuck.new
    @categories = chuck.categories
    puts 'categories'
    puts @categories
  end
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_action :set_joke, only: [:show, :edit, :update, :destroy]

  # GET /jokes
  # GET /jokes.json
  def index
    @jokes = Joke.all

  end

  def random
    chuck = Api::Chuck.new
    @jokes = chuck.random
    puts @jokes
    render 'index'
  end

  def search
    chuck = Api::Chuck.new
    @jokes = chuck.search(params[:query])
    render 'index'
  end

  def category
    chuck = Api::Chuck.new
    puts params[:category]
    @jokes = chuck.category(params[:category])
    puts @jokes
    render 'index'
  end

  # GET /jokes/1
  # GET /jokes/1.json
  def show
  end

  # GET /jokes/new
  def new
    @joke = Joke.new
  end

  # GET /jokes/1/edit
  def edit
  end

  # POST /jokes
  # POST /jokes.json
  def create
    @joke = Joke.new(joke_params)

    respond_to do |format|
      if @joke.save
        format.html { redirect_to @joke, notice: 'Joke was successfully created.' }
        format.json { render :show, status: :created, location: @joke }
      else
        format.html { render :new }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jokes/1
  # PATCH/PUT /jokes/1.json
  def update
    respond_to do |format|
      if @joke.update(joke_params)
        format.html { redirect_to @joke, notice: 'Joke was successfully updated.' }
        format.json { render :show, status: :ok, location: @joke }
      else
        format.html { render :edit }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1
  # DELETE /jokes/1.json
  def destroy
    @joke.destroy
    respond_to do |format|
      format.html { redirect_to jokes_url, notice: 'Joke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joke
      @joke = Joke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joke_params
      params.require(:joke).permit(:icon_url, :url, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/views/home/index.html.erb
<h1>Chuck Norris API</h1>
<%= button_tag(:type => 'button') do %>
    <% link_to t('tags.random_search'), random_joke_path(@joke) %>
<% end %>
<%= form_tag(search_joke_path) do %>
    <%=t('tags.texts') %> <%= text_field_tag :query %>
    <%= submit_tag t('tags.search') %>
<% end %>
<%= form_tag(category_joke_path) do %>
    <%= t('tags.categories') %> <%= select_tag "category", options_for_select(@categories) %>
    <%= submit_tag t('tags.search') %>
<% end %>

app/views/jokes/_form.html.erb
<%= form_with(model: joke, local: true) do |form| %>
  <% if joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
      <% joke.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :icon_url %>
    <%= form.text_field :icon_url %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jokes/edit.html.erb
<h1>Editing Joke</h1>

<%= render 'form', joke: @joke %>

<%= link_to 'Show', @joke %> |
<%= link_to 'Back', jokes_path %>

app/views/jokes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jokes</h1>

<table>
  <thead>
    <tr>
      <th>Icon url</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jokes.each do |joke| %>
      <tr>     
        <td><%= image_tag(joke.icon_url) %></td>
        <td><%= joke.value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jokes/new.html.erb
<h1>New Joke</h1>

<%= render 'form', joke: @joke %>

<%= link_to 'Back', jokes_path %>

app/views/jokes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Icon url:</strong>
  <%= @joke.icon_url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @joke.url %>
</p>

<p>
  <strong>Value:</strong>
  <%= @joke.value %>
</p>

<%= link_to 'Edit', edit_joke_path(@joke) %> |
<%= link_to 'Back', jokes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chucknorries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>